WTBUILD-268 Remove redundant wt_defs.py and centralize in wiredtiger
wiredtiger/layercparse pull request #1
Opened 2024-12-16 02:25 UTC by Siddhartha8899

2024-12-16 02:30 UTC, Siddhartha8899 commented on check_sources.py
> +
Don't know if there a better way to do this, but didn't wanna spend too much time on this.

It simply searches for the first occurrence of `dist/access_check` and adds in as `PYTHONPATH`, so that it could import `wt_defs.py`.

2024-12-16 07:56 UTC, Siddhartha8899 commented on check_sources.py
> +def load_wt_defs(rootPath):
this function is redundant in all three files, @ershov is there a common place for this function.

2024-12-16 08:46 UTC, Siddhartha8899 commented on check_sources.py
> +    wt_defs_path = os.path.join(rootPath, 'dist', 'access_check', 'wt_defs.py')
We will have to change these paths once https://github.com/wiredtiger/wiredtiger/pull/11335 is merged.

2024-12-17 21:58 UTC, ershov requested changes

2024-12-17 21:58 UTC, ershov commented on check_sources.py
> +def load_wt_defs(rootPath):
Yes, `workspace.py` is a good home for this function.  

Please use the `file_content()` function to read the file.  

Also, consider using `eval` instead of `exec`. That way, `wt_defs` would look like:  
```python
{
  "extraFiles": ["src/include/wiredtiger.in"],
  "modules": [
    # Modules in subdirectories of src/
    Module("block"),
    Module("block_cache", fileAliases=["block_chunkcache"], sourceAliases=["blkcache", "bm"]),
    ...
  ],
  "extraMacros": [
    ...
  ],
}
```
with `eval()` returning a Python dictionary.

This approach provides a cleaner and safer configuration structure.

2024-12-17 21:58 UTC, ershov commented on check_sources.py
> +    wt_defs_path = os.path.join(rootPath, 'dist', 'access_check', 'wt_defs.py')
The good thing is that we’re not currently forced to sync these kinds of changes :) We can do it either way.

2024-12-18 00:20 UTC, Siddhartha8899 commented on check_sources.py
> +def load_wt_defs(rootPath):
I tried using eval, but there is an import in wt_defs.py, hence it wasnt working. I can split that part when I read the file, does that sound good?

Exec looks a bit neater, but I can see why eval is a better choice.

2024-12-18 00:49 UTC, Siddhartha8899 commented on check_sources.py
> +def load_wt_defs(rootPath):
Updated in [05cfab3](https://github.com/wiredtiger/layercparse/pull/1/commits/05cfab3d9c8ef033d9bd952929e61a7c5f48e13c)

2024-12-19 00:14 UTC, ershov commented on refactor.py
> +    wt_defs = load_wt_defs(rootPath, WT_DEFS_RELATIVE_PATH)
Can we use `load_code_config` and `code_config` here (and in other places) so that it doesn't directly refer to wt?

2024-12-19 06:53 UTC, Siddhartha8899 commented on refactor.py
> +    wt_defs = load_wt_defs(rootPath, WT_DEFS_RELATIVE_PATH)
updated in [4e04c79](https://github.com/wiredtiger/layercparse/pull/1/commits/4e04c793e88806cfbc4e542df5574654f2f8efe8)

2024-12-20 00:04 UTC, ershov approved these changes
Thanks Sid!
The first pool request is in! Yayy! :)

2024-12-20 00:04 UTC, ershov commented on setup.py
> +    version = re.search(r'LAYERCPARSE_VERSION\s*=\s*"([^"]+)"', f.read()).group(1)
Efficiency nit: this regex is more performant if written as:
```python
r'LAYERCPARSE_VERSION\s*+=\s*+"([^"]++)"'
```

(note that extra `+`)

But this is not a critical path, so it's fine.

2024-12-24 01:23 UTC, merged